audit_header: false
title: "Florida's Best Real Estate Training - Alex Haigh"
description: Alex Haigh, a top Real Estate Agent in Florida, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Events
    url: https://www.eventbrite.com/o/hosted-by-alexander-haigh-27320440689
  - title: Free Strategy Call
    url: /strategy-call/
client:
  name: Alex Haigh
  title:
  license_number:
  about_markdown: |
    Alexander is a 3rd generation real estate professional. He has lived in South Florida for over 10 years and has been working with buyers and sellers full time during that time. His experience includes working with luxury home sellers, investors, and first time home buyers. Alexander owns and manages a real estate team and full time staff. Alexander and his team are a full service client focused group that can handle all of your real estate needs.
  market: Florida
  brand: The Haigh Group
  brokerage: eXp Realty
  address: 200 Southwest Atlanta Avenue<br>Stuart, FL 34994
  phone: 772-240-0997
  phone_type:
  phone2:
  phone2_type:
  email: alexanderhaighrealtor@gmail.com
  url: http://www.thehaighgroup.com

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Looking to Build Your Real Estate Career?"
    CTA_text: "Let's talk about how The Haigh Group can take your business to new heights."
    CTA_link_text: "Free Strategy Session"
    CTA_url: /contact/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/002.jpg
#     CTA_title2: "Join Our Team"
#     CTA_text2: "Sell more homes by joining forces with the our dynamic real estate company."
#     CTA_link_text2: "Career Info"
#     CTA_url2: /

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: true
  facebook_url: https://www.facebook.com/thehaighgrouprealty/
  linkedin_url: http://www.linkedin.com/pub/alex-haigh/0/540/6b1/
  gplus_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/Alex-Haigh/
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Florida Real Estate Podcast with Alex Haigh'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Florida Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from The Haigh Group - your professional Florida Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Florida, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Alex Haigh'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Florida Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#f5821f'
  theme_color: '#17244c'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#f5821f'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
